apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-sm-laptop
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 96.232.121.104/32